# Form implementation generated from reading ui file 'D:\__MY_PROJECT__\Python\ControlAxle\ui\base_qt_ui\ui_graph.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Graph(object):
    def setupUi(self, Graph):
        Graph.setObjectName("Graph")
        Graph.resize(1130, 140)
        Graph.setMinimumSize(QtCore.QSize(1130, 140))
        Graph.setMaximumSize(QtCore.QSize(1130, 140))
        self.button_check = QtWidgets.QPushButton(parent=Graph)
        self.button_check.setGeometry(QtCore.QRect(1070, 100, 50, 20))
        self.button_check.setObjectName("button_check")
        self.lineEdit = QtWidgets.QLineEdit(parent=Graph)
        self.lineEdit.setGeometry(QtCore.QRect(60, 100, 1000, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_code = QtWidgets.QLabel(parent=Graph)
        self.label_code.setGeometry(QtCore.QRect(10, 105, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_code.setFont(font)
        self.label_code.setObjectName("label_code")
        self.label_system1 = QtWidgets.QLabel(parent=Graph)
        self.label_system1.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_system1.setFont(font)
        self.label_system1.setObjectName("label_system1")
        self.label_system2 = QtWidgets.QLabel(parent=Graph)
        self.label_system2.setGeometry(QtCore.QRect(10, 65, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_system2.setFont(font)
        self.label_system2.setObjectName("label_system2")

        self.retranslateUi(Graph)
        QtCore.QMetaObject.connectSlotsByName(Graph)

    def retranslateUi(self, Graph):
        _translate = QtCore.QCoreApplication.translate
        Graph.setWindowTitle(_translate("Graph", "Dialog"))
        self.button_check.setText(_translate("Graph", "Cheсk"))
        self.label_code.setText(_translate("Graph", "Code"))
        self.label_system1.setText(_translate("Graph", "SYS1"))
        self.label_system2.setText(_translate("Graph", "SYS2"))
