# Form implementation generated from reading ui file 'D:\__MY_PROJECT__\Python\qlayout_example_not_mine\ui\base_qt_ui\ui_graph.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Graph(object):
    def setupUi(self, Graph):
        Graph.setObjectName("Graph")
        Graph.resize(1120, 80)
        Graph.setMinimumSize(QtCore.QSize(12, 12))
        self.button_reset = QtWidgets.QPushButton(parent=Graph)
        self.button_reset.setGeometry(QtCore.QRect(525, 50, 70, 20))
        self.button_reset.setObjectName("button_reset")

        self.retranslateUi(Graph)
        QtCore.QMetaObject.connectSlotsByName(Graph)

    def retranslateUi(self, Graph):
        _translate = QtCore.QCoreApplication.translate
        Graph.setWindowTitle(_translate("Graph", "Dialog"))
        self.button_reset.setText(_translate("Graph", "Reset"))
